### ISSUE TITLE
Does not account for disabled state of input

### ISSUE THREAD

**Issue by dwightdegroff** [rpocklin/angular-confirmable#1]
When an input (e.g., button is disable), angular-confirmable does not take notice. It changes to the "confirming-text" and then executes the "when-confirmed" action if clicked again. This case comes up when a button is conditionally disabled (e.g., Some users do not have authorization to delete an entry).

The following is a simplified example in which the button is always disabled, but confirmable does not respect that state.

``` html
<confirmable when-confirmed="delete" unconfirmed-text="DELETE!"
             confirming-text="Are you sure?" reset-delay="3000">
  <button id="deleteButton" class="btn btn-danger"
          ng-disabled="true">
    <confirmable-outlet></confirmable-outlet>
  </button>
</confirmable>
```

**Comment by rpocklin** [comment]
If you read the docs you'll see there is a `disabled` attribute on the directive (not the button) which is watched and give you the behaviour you expect.  So don't use `ng-disabled` on the button, use `<confirmable disabled="...">` instead.
